apiVersion: v2
name: my-ingress-chart
description: A Helm chart for deploying NGINX Ingress Controller and application Ingresses
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: ingress-nginx
    version: "4.10.1"
    repository: "https://kubernetes.github.io/ingress-nginx"