ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerSourceRanges: 5.29.17.230/32

frontendIngress:
  host: "dataloopwebapp.com"
  tlsSecretName: "frontend-tls-secret"
  serviceName: "frontend"
  servicePort: 80

appNamespace: "services"