ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      loadBalancerSourceRanges:
        - "5.29.17.230/32"

frontendIngress:
  host: "35.184.100.128"
  tlsSecretName: "frontend-tls-secret"
  serviceName: "frontend"
  servicePort: 80
appNamespace: "services"