apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        iam.gke.io/gcp-service-account: gke-dataloop-project-service-a@dataloop-project-463316.iam.gserviceaccount.com
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: MONGO_URL
          value: mongodb://mongo:{{ .Values.mongodb.port }}
