apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: services
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.servicePort }}
