apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: services
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          args: {{ toJson .Values.backend.args }}
          ports:
            - containerPort: {{ .Values.backend.servicePort }}
