apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: services
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.servicePort }}
  type: LoadBalancer
