apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
#      serviceAccountName: .Values.serviceAccount.name
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
	imagePullPolicy: Always 
        ports:
        - containerPort: {{ .Values.frontend.port }}
