apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "mongodb-role"
        vault.hashicorp.com/agent-inject-template-mongo-url: |
          {{ "{{" }}- with secret "database/creds/mongodb-database-role" -{{ "}}" }}
          mongodb://{{ "{{" }} .Data.username {{ "}}" }}:{{ "{{" }} .Data.password {{ "}}" }}@mongo.services.svc.cluster.local:27017
          {{ "{{" }}- end -{{ "}}" }}
    spec:
#      serviceAccountName:  .Values.serviceAccount.name
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: MONGO_URL
          value: "file:///vault/secrets/mongo-url"