namespace: services

frontend:
  image: gcr.io/your-gcp-project-id/frontend-app
  replicas: 2
  servicePort: 80
  containerPort: 80

backend:
  image: gcr.io/your-gcp-project-id/backend-app
  replicas: 2
  servicePort: 3000
  containerPort: 3000

db:
  image: postgres:14-alpine
  username: myuser
  password: mypassword
  database: visits
  pvcSize: 5Gi
  servicePort: 5432
